### ISSUE TITLE
JOSS review: add a basic example to your paper

### ISSUE THREAD

**Issue by vankesteren** [aneeshnaik/lintsampler#9]
For JOSS submissions, I always like it when there is a basic usage example in the paper itself. It isn't a formal requirement per se, so feel free to ignore this point and close the issue, but a preference on my part.

**Comment by aneeshnaik** [comment]
We have added a basic example to the paper in the joss-major branch (PR #12)

**Comment by aneeshnaik** [comment]
Closed in PR #12
